[build]
  publish = "public"
  command = "node ../scripts/build-public.cjs"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."reminders"]
  schedule = "*/5 * * * *"
